all:
	assemble.sh proc.asm  && vtest t_proc_pipe_bench


clean:
	rm -f *.ptrace *.trace *.lst *.img *.dmem *.reg transcript *.vcd *.wlf test.out *.log *.out *.vstf *.svf *.dat dumpfile *.mti *.mpf 
	rm -f `find .. | grep "\(#\)\|\(~\)"`   


