all:
	assemble.sh proc.asm  && vtest t_proc_bench


clean:
	rm -f *.ptrace *.trace *.lst *.img *.dmem *.reg transcript *.vcd *.wlf test.out *.log *.out *.vstf
	rm -f `find .. | grep "\(#\)\|\(~\)"`   


